// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9325d71a-f1de-4159-9bdd-f561cf7086ce",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_5eyjU40sz",
    "aws_user_pools_web_client_id": "4dd1hrc271eo3l6b1ivfj2ov50",
    "oauth": {},
    "aws_user_files_s3_bucket": "pet-reviews-files-prod",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
